#!/bin/sh
### BEGIN INIT INFO
# Provides:          angharad
# Required-Start:    $network $time
# Required-Stop:     $network $time
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the angharad daemon
# Description:
### END INIT INFO

user=pi
group=pi
prefix=/usr/bin
exec_prefix=${prefix}
angharad=${prefix}/angharad
angharadconf=--config=/etc/angharad.conf
pidfile=/var/run/angharad.pid

case "$1" in
  stop)
    echo -n "Stopping angharad "
    killall -9 angharad
    echo "OK"
    ;;

  start)
    echo -n "Starting Angharad "
    touch $pidfile
    chown $user:$group $pidfile
    start-stop-daemon --start --quiet --make-pidfile --pidfile $pidfile \
      --chuid $user:$group --background --exec $angharad -- $angharadconf
    echo "OK"
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
